# Project: SKOBAN
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"D:/Programme/Dev-Cpp/lib" ../../../../Programme/Dev-Cpp/lib/liballeg.dll.a  -mwindows 
INCS =  -I"D:/Programme/Dev-Cpp/include" 
CXXINCS =  -I"D:/Programme/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/Programme/Dev-Cpp/include/c++/3.4.2/backward"  -I"D:/Programme/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"D:/Programme/Dev-Cpp/include/c++/3.4.2"  -I"D:/Programme/Dev-Cpp/include" 
BIN  = SKOBAN.exe
CXXFLAGS = $(CXXINCS)   -fexpensive-optimizations -O3 -mwindows
CFLAGS = $(INCS)   -fexpensive-optimizations -O3 -mwindows
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before SKOBAN.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "SKOBAN.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
